version: 1.0.0
name: azure_identity_provider
description: A sample command-line application.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auth_cubit: 
    path: ../auth_cubit
  # azure_identity: ^0.0.5
  stack_trace: ^1.11.0
  talker: ^4.4.1
  talker_bloc_logger: ^4.4.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
