name: Setup Flutter
description: Setup of the flutter application

inputs:
  cloudsmith-access-token: 
    required: true
    description: 'Needed to get evoleen/evoleen_fhir'

runs:
  using: composite
  steps:
    - name: Read Flutter version from file
      id: flutter_version
      shell: sh
      run: |
        FLUTTER_VERSION=$(jq -r '.flutter' .fvmrc)
        echo "Flutter version: $FLUTTER_VERSION"
        echo "::set-output name=flutter_version::$FLUTTER_VERSION"
    - name: ☕ Java Setup
      uses: actions/setup-java@v4
      with:
        java-version: "17.x"
        distribution: "adopt"
    - name: 🦅 Flutter Setup
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "${{ steps.flutter_version.outputs.flutter_version }}"
        channel: "stable"
    - name: 🩺 Flutter Doctor
      shell: sh
      run: flutter doctor -v
    - name: 📦 Fetch Packages
      shell: sh
      run: flutter pub get
