version: 0.0.1
name: flutter_fastapp
description: "flutter_fastapp"
publish_to: none
homepage: https://github.com/FlutterBesties/flutter_fastapp
repository: https://github.com/FlutterBesties/flutter_fastapp
issue_tracker: https://github.com/FlutterBesties/flutter_fastapp

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  args: 2.4.2
  auth_cubit:
    hosted: https://dart.cloudsmith.io/flutterbesties/dart_packages/
    version: ^0.0.9
  auth_cubit_biometrics:
    hosted: https://dart.cloudsmith.io/flutterbesties/dart_packages/
    version: ^0.0.10
  auth_cubit_firebase:
    hosted: https://dart.cloudsmith.io/flutterbesties/dart_packages/
    version: ^0.0.2
  built_collection: 5.1.1
  collection: 1.18.0
  firebase_auth: 4.19.2
  firebase_core: 2.30.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.5
  flutter_dotenv: 5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.4.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: 2.4.1
  get_it: 7.7.0
  go_router: 13.2.4
  intl: 0.19.0
  local_auth: 2.2.0
  path: 1.9.0
  pub_semver: 2.1.4
  shared_preferences: 2.2.3
  stack_trace: 1.11.1
  talker_bloc_logger: 4.1.3
  talker_dio_logger: 4.1.3
  talker_flutter: 4.1.3
  time_machine: 0.9.17

dev_dependencies:
  bloc_test: 9.1.7
  build_runner: 2.4.9
  dartz: 0.10.1
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.2
  flutter_oss_licenses: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  go_router_builder: 2.5.1
  intl_utils: 2.8.7
  mocktail: 1.0.3
  remove_from_coverage: 2.0.0
  
dependency_overrides:
  analyzer: 6.2.0
  intl: 0.18.1
  time_machine:
    git:
      url: https://github.com/evoleen/time_machine.git
      ref: fix-canonical-timezones-for-web

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  use_deferred_loading: false