version: 0.0.1
name: firearrow_admin_app
description: "firearrow_admin_app"
publish_to: none
homepage: https://github.com/evoleen/firearrow_admin_app
repository: https://github.com/evoleen/firearrow_admin_app
issue_tracker: https://github.com/evoleen/firearrow_admin_app

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  args: 2.5.0
  auth_cubit:
    hosted:
      url: https://dart.cloudsmith.io/evoleen/auth_cubit
      name: auth_cubit
    version: 0.0.3
  # azure_identity: 0.0.3
  built_collection: 5.1.1
  collection: 1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.3.7
  freezed_annotation: 2.4.4
  get_it: 7.7.0
  google_fonts: 6.2.1
  go_router: 14.2.3
  intl: 0.19.0
  path: 1.9.0
  pub_semver: 2.1.4
  shared_preferences: 2.3.1
  stack_trace: 1.11.1
  talker: 4.4.1
  talker_bloc_logger: 4.4.1
  talker_flutter: 4.4.1

dev_dependencies:
  bloc_test: 9.1.7
  build_runner: 2.4.12
  dartz: 0.10.1
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.2
  flutter_oss_licenses: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 3.0.0-0.0.dev
  go_router_builder: 2.7.1
  intl_generator: 0.4.1
  mocktail: 1.0.4
  remove_from_coverage: 2.0.0
  
dependency_overrides:
  analyzer: 6.2.0
  intl: 0.18.1

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/