version: 0.0.1
name: fire_scribe
description: "fire_scribe"
publish_to: none
homepage: https://github.com/evoleen/fire_scribe
repository: https://github.com/evoleen/fire_scribe
issue_tracker: https://github.com/evoleen/fire_scribe/issues

environment:
  sdk: ^3.5.0
  flutter: ^3.24.3

dependencies:
  args: 2.6.0
  azure_identity: 0.0.5+1
  built_collection: 5.1.1
  collection: 1.18.0
  dio: 5.7.0
  diff_match_patch: 0.4.1
  fhir_rest_client:
    git:
      url: https://github.com/evoleen/fhir_rest_client.git
      ref: add_docs
  fhir: 0.12.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_code_editor: 0.3.2
  flutter_highlight: 0.7.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 2.4.4
  get_it: 7.7.0
  google_fonts: 6.2.1
  go_router: 14.2.8
  highlight: 0.7.0
  infinite_scroll_pagination: 4.0.0
  intl: 0.19.0
  material_symbols_icons: 4.2789.0
  package_info_plus: 8.1.1
  path: 1.9.0
  pub_semver: 2.1.4
  shared_preferences: 2.3.2
  stack_trace: 1.11.1
  talker: 4.4.1
  talker_bloc_logger: 4.4.1
  talker_dio_logger: 4.4.1
  talker_flutter: 4.4.1

dev_dependencies:
  bloc_test: 9.1.7
  build_runner: 2.4.13
  dartz: 0.10.1
  flutter_launcher_icons: 0.14.1
  flutter_lints: 5.0.0
  flutter_oss_licenses: 3.0.2
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  go_router_builder: 2.7.1
  intl_translation: 0.20.0
  mocktail: 1.0.4
  remove_from_coverage: 2.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/app/