name: Sanity Check
description: Does the testing for the Flutter application and uploading a coverage

runs:
  using: composite
  steps:
    - name: 🧪 Test with Coverage
      shell: sh
      run: flutter test --coverage
    - name: Clean up coverage
      shell: sh
      run: flutter pub run remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$'
    - name: Install coverde cli (for code coverage report & checking)
      shell: sh
      run: dart pub global activate --source git https://github.com/mrverdant13/coverde.git --git-path=packages/coverde_cli --git-ref=24d3dd8
    - name: Generate code coverage report
      shell: sh
      run: coverde report --markdown report.md

