version: 0.0.1
name: auth_cubit
description: "A new Dart package project."
publish_to: https://dart.cloudsmith.io/evoleen/auth_cubit
homepage: https://github.com/evoleen/auth_cubit
repository: https://github.com/evoleen/auth_cubit
issue_tracker: https://github.com/evoleen/auth_cubit

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  args: ^2.4.2
  bloc: ^8.1.4
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  pub_semver: ^2.1.4

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  freezed: ^2.4.7
  lints: ^3.0.0
  mocktail: ^1.0.3
  remove_from_coverage: ^2.0.0
  test: ^1.25.3
